version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: task-management-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-management-network

volumes:
  postgres_data:

networks:
  task-management-network:
    driver: bridge 