version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: task-management-postgres
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-task_management}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - task-management-network

volumes:
  postgres_data:

networks:
  task-management-network:
    driver: bridge 